### ISSUE TITLE
Cannot init a project with Vue3 Vite

### ISSUE THREAD

**Issue by YoYomec** [retejs/rete-kit#24]
This is my error message :
```
npx rete-kit app
? Name test2
? Stack (framework) Vue.js Vite
? Version 3
? Select features Vue render, Order nodes, Zoom at, Auto arrange, Dataflow engine, Readonly, Selectable nodes, Context menu, Minimap, Reroute

Vue.js - The Progressive JavaScript Framework

√ Add TypeScript? ... Yes
√ Add JSX Support? ... No
√ Add Vue Router for Single Page Application development? ... No
√ Add Pinia for state management? ... No
√ Add Vitest for Unit Testing? ... No
√ Add an End-to-End Testing Solution? » No
√ Add ESLint for code quality? ... No

Scaffolding project in C:\Users\<me>\Documents\Code\Mediator\Nodal\Rete\test2...

Done. Now run:

  cd test2
  npm install
  npm run dev

npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Users\<me>\Documents\Code\Mediator\Nodal\Rete/package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\<me>\Documents\Code\Mediator\Nodal\Rete\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in: C:\Users\<me>\AppData\Local\npm-cache\_logs\2023-12-24T12_01_35_616Z-debug-0.log
C:\Users\<me>\AppData\Local\npm-cache\_npx\04f87544ed17fde2\node_modules\execa\lib\error.js:60
                error = new Error(message);
                        ^

Error: Command failed with exit code 4294963238: npm --prefix test2 i
    at makeError (C:\Users\<me>\AppData\Local\npm-cache\_npx\04f87544ed17fde2\node_modules\execa\lib\error.js:60:11)
    at handlePromise (C:\Users\<me>\AppData\Local\npm-cache\_npx\04f87544ed17fde2\node_modules\execa\index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async VueViteBuilder.create (C:\Users\<me>\AppData\Local\npm-cache\_npx\04f87544ed17fde2\node_modules\rete-kit\bin\app\stack\vue\vite.js:21:9)
    at async createApp (C:\Users\<me>\AppData\Local\npm-cache\_npx\04f87544ed17fde2\node_modules\rete-kit\bin\app\index.js:100:9) {
  shortMessage: 'Command failed with exit code 4294963238: npm --prefix test2 i',
  command: 'npm --prefix test2 i',
  escapedCommand: 'npm --prefix test2 i',
  exitCode: 4294963238,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

Node.js v18.18.1
```
I don't know if it's the computer or me that is bugging, but I don't know how to fix this.

**Comment by YoYomec** [comment]
Thx, works now :)
